/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicmanagement;

import java.awt.Component;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;
public class ThemBenhNhan extends javax.swing.JFrame {

    /**
     * Creates new form ThemBenhNhan
     */
    private static int SoBenhNhan;
    private static String CMND = "";
    public ThemBenhNhan() throws SQLException {
        initComponents();
        SoBenhNhan = 0;
        DatabaseConnection DTBC = new DatabaseConnection();
        Connection conn = DTBC.getConnection(this);
        Statement stm = conn.createStatement();
        ResultSet rs = stm.executeQuery("SELECT MaBenhNhan FROM BenhNhan");
        while (rs.next())
        {
            MaBenhNhan.addItem(rs.getString("MaBenhNhan"));
            SoBenhNhan++;
        }
        rs.close();
        stm.close();
        conn.close();
    }
    
    public ThemBenhNhan(String CMND) throws SQLException {
        initComponents();
        SoBenhNhan = 0;
        DatabaseConnection DTBC = new DatabaseConnection();
        Connection conn = DTBC.getConnection(this);
        Statement stm = conn.createStatement();
        ResultSet rs = stm.executeQuery("SELECT MaBenhNhan FROM BenhNhan");
        this.CMND = CMND;
        while (rs.next())
        {
            MaBenhNhan.addItem(rs.getString("MaBenhNhan"));
            SoBenhNhan++;
        }
        rs.close();
        stm.close();
        conn.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Tentrang2 = new javax.swing.JLabel();
        MaBenhNhan = new javax.swing.JComboBox<>();
        TenBenhNhan = new javax.swing.JTextField();
        GioiTinh = new javax.swing.JComboBox<>();
        NamSinh = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DiaChi = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 84, 42));
        jLabel1.setText("Mã bệnh nhân");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 84, 42));
        jLabel2.setText("Tên bệnh nhân");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 84, 42));
        jLabel3.setText("Giới tính");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 84, 42));
        jLabel4.setText("Năm sinh");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 84, 42));
        jLabel5.setText("Địa chỉ");

        Tentrang2.setBackground(new java.awt.Color(255, 255, 255));
        Tentrang2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Tentrang2.setForeground(new java.awt.Color(0, 84, 42));
        Tentrang2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Tentrang2.setText("THÔNG TIN BỆNH NHÂN");

        MaBenhNhan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NULL" }));
        MaBenhNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaBenhNhanActionPerformed(evt);
            }
        });

        GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        DiaChi.setColumns(20);
        DiaChi.setRows(5);
        jScrollPane1.setViewportView(DiaChi);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setForeground(new java.awt.Color(0, 99, 28));
        jButton2.setText("Thêm");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(MaBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TenBenhNhan)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Tentrang2)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Tentrang2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MaBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TenBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MaBenhNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaBenhNhanActionPerformed
        String s = MaBenhNhan.getSelectedItem().toString();
        if (s != "NULL") {
            DatabaseConnection DTBC = new DatabaseConnection();
            Connection conn = null;
            Statement stm = null;
            ResultSet rs = null;
            try {
                conn = DTBC.getConnection(this);
                stm = conn.createStatement();
                rs = stm.executeQuery("SELECT TenBenhNhan, GioiTinh, NamSinh, DiaChi FROM BenhNhan WHERE MaBenhNhan = '" + s + "'");
                while (rs.next()) {
                    TenBenhNhan.setText(rs.getString("TenBenhNhan"));
                    GioiTinh.setSelectedItem(rs.getString("GioiTinh"));
                    NamSinh.setText(String.valueOf(rs.getInt("NamSinh")));
                    DiaChi.setText(rs.getString("DiaChi"));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.toString(), "Lỗi kết nối cơ sở dữ liệu", ERROR_MESSAGE);
            }
        }
        else
        {
            TenBenhNhan.setText("");
            GioiTinh.setSelectedItem("Nam");
            NamSinh.setText("");
            DiaChi.setText("");
        }
    }//GEN-LAST:event_MaBenhNhanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (TenBenhNhan.getText().isBlank() || NamSinh.getText().isBlank()|| DiaChi.getText().isBlank())
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin", "Thông tin chưa đầy đủ", 1);
        }
        else {
            try {
                DatabaseConnection DTBC = new DatabaseConnection();
                Connection conn = DTBC.getConnection(this);
                Statement stm = conn.createStatement();
                String MaBN = MaBenhNhan.getSelectedItem().toString();
                if (MaBenhNhan.getSelectedItem().toString() == "NULL") {
                    
                    if (SoBenhNhan + 1 < 10) {
                        MaBN = "BN00" + String.valueOf(SoBenhNhan+1);
                    } else {
                        MaBN = "BN0" + String.valueOf(SoBenhNhan+1);
                    }
                    stm.executeUpdate("INSERT INTO BENHNHAN VALUES ('" + MaBN + "',N'" + TenBenhNhan.getText() + "',N'" + GioiTinh.getSelectedItem().toString() + "'," + NamSinh.getText() + ",N'" + DiaChi.getText() + "')");
                    
                }
                else
                {
                    stm.executeUpdate("UPDATE BENHNHAN SET TenBenhNhan = N'"+TenBenhNhan.getText()+"', GioiTinh = N'"+GioiTinh.getSelectedItem().toString()+"', NamSinh = "+NamSinh.getText().toString()+", DiaChi = N'"+DiaChi.getText()+"' WHERE MaBenhNhan = '"+MaBenhNhan.getSelectedItem().toString()+"'");
                }
                stm.executeUpdate("SET DATEFORMAT DMY");
                ResultSet rs = stm.executeQuery("SELECT COUNT(*) FROM PHIEUKHAMBENH");
                int SoPhieu = 0;
                while (rs.next()) SoPhieu = rs.getInt(1) + 1;
                String NgayKham = String.valueOf(LocalDate.now().getDayOfMonth())+"/"+ String.valueOf(LocalDate.now().getMonthValue()) + "/" + String.valueOf(LocalDate.now().getYear());
                String MaPhieu = "PKB"+String.valueOf(SoPhieu);
                stm.executeUpdate("INSERT INTO PHIEUKHAMBENH(MaPhieuKhamBenh, MaBenhNhan, NgayKham) VALUES ('"+MaPhieu+"','"+MaBN+"','"+NgayKham+"')");
                JOptionPane.showMessageDialog(this, "Thêm bệnh nhân vào danh sách khám bệnh thành công","Thêm thành công", 1);
                this.setVisible(false);
                DanhSachKhamBenh frame = new DanhSachKhamBenh();
                frame.setVisible(true);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.toString(), "Lỗi kết nối cơ sở dữ liệu", ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new ThemBenhNhan().setVisible(true);
                } catch (SQLException ex) {
                    
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DiaChi;
    private javax.swing.JComboBox<String> GioiTinh;
    private javax.swing.JComboBox<String> MaBenhNhan;
    private javax.swing.JTextField NamSinh;
    private javax.swing.JTextField TenBenhNhan;
    private javax.swing.JLabel Tentrang2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
