/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

package clinicmanagement;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
/**
 *
 * @author Dell
 */
public class ThemDV extends javax.swing.JDialog {

    /** Creates new form ThemDV */
    public ThemDV(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.white);
    }
    public int LUU()throws SQLException{
        DatabaseConnection DTBC = new DatabaseConnection();
        Connection conn = DTBC.getConnection(this);
        Statement stm = conn.createStatement();
                
        String tendv = ten.getText();
        
        stm.executeUpdate("INSERT INTO DONVITINH  VALUES ( N'" + tendv +  "');");
       
        stm.close();
        conn.close();
        return 1;
    }  
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LUU = new javax.swing.JButton();
        TROLAI = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ten = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LUU.setBackground(new java.awt.Color(255, 204, 204));
        LUU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LUU.setForeground(new java.awt.Color(0, 99, 28));
        LUU.setText("Lưu");
        LUU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LUUMouseClicked(evt);
            }
        });
        getContentPane().add(LUU, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 209, 83, 40));

        TROLAI.setBackground(new java.awt.Color(255, 204, 204));
        TROLAI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TROLAI.setForeground(new java.awt.Color(0, 99, 28));
        TROLAI.setText("Quay lại");
        TROLAI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TROLAIMouseClicked(evt);
            }
        });
        getContentPane().add(TROLAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 209, 106, 40));

        ten.setColumns(20);
        ten.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ten.setRows(5);
        jScrollPane1.setViewportView(ten);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 24, 465, 167));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LUUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LUUMouseClicked
        try
        {
            if(LUU()==1) JOptionPane.showMessageDialog(this, "Bạn đã lưu thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new DanhSachDonViTinh().setVisible(true);
                }
            });
            this.dispose();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this, e.toString(), "Lỗi kết nối cơ sở dữ liệu", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LUUMouseClicked

    private void TROLAIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TROLAIMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhSachDonViTinh().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_TROLAIMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThemDV dialog = new ThemDV(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LUU;
    private javax.swing.JButton TROLAI;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ten;
    // End of variables declaration//GEN-END:variables

}
